// Auto-generated by training/distill.py
// Do not edit manually -- re-run distillation to update.
//
// Distilled from checkpoint, 5 roles
// When a weight is null, the original hand-tuned value is used (fallback).

export const LEARNED_WEIGHTS = {
  "SNIPER": {
    "night": {
      "inverseSusp": 0.552736,
      "policeProb": 0.664105,
      "speakRatio": 0.0,
      "protectedPenalty": 0.123592,
      "grudgeAvoid": 0.116921
    }
  },
  "DOCTOR": {
    "night": {
      "policeProb": -0.491551,
      "blueProb": -0.823509,
      "speakRatio": 0.0,
      "votePressure": -0.002132
    }
  },
  "POLICE": {
    "night": {
      "killerProb": 0.098899,
      "sniperProb": -0.014834,
      "kidnapProb": -0.054691,
      "redProb": 0.035761,
      "silentRedLean": 0.0,
      "votePressure": -0.005125,
      "voteTogether": 0.008024
    }
  },
  "KILLER": {
    "night": {
      "policeProb": 0.351471,
      "doctorProb": -0.86688,
      "agentProb": 0.123465,
      "speakRatio": 0.0,
      "suspicion": 0.417544,
      "votePressure": -0.004951,
      "theyAccusedMe": 0.0,
      "voteTogether": -0.005675
    }
  }
};

/**
 * Get a learned weight, falling back to the hand-tuned default if missing.
 */
export function getWeight(role, phase, feature, handTunedDefault) {
  const rw = LEARNED_WEIGHTS[role];
  if (!rw) return handTunedDefault;
  const pw = rw[phase];
  if (!pw) return handTunedDefault;
  const val = pw[feature];
  return val !== null && val !== undefined ? val : handTunedDefault;
}
