// Auto-generated by training/distill.py
// Do not edit manually -- re-run distillation to update.
//
// Distilled from checkpoint, 4 roles
// When a weight is null, the original hand-tuned value is used (fallback).

export const LEARNED_WEIGHTS = {
  "KILLER": {
    "night": {
      "policeProb": 0.019859,
      "doctorProb": 0.029415,
      "agentProb": -0.026047,
      "speakRatio": 0.035304,
      "suspicion": -0.016742,
      "blueProb": 0.035351
    }
  },
  "POLICE": {
    "night": {
      "killerProb": 0.036633,
      "sniperProb": 0.149325,
      "kidnapProb": 0.013285,
      "redProb": -0.01073,
      "silentRedLean": 0.01195
    }
  },
  "SNIPER": {
    "night": {
      "inverseSusp": -0.032551,
      "policeProb": 0.024914,
      "speakRatio": 0.028733,
      "protectedPenalty": -0.000815
    }
  },
  "DOCTOR": {
    "night": {
      "policeProb": 0.029668,
      "blueProb": -0.074127,
      "speakRatio": 0.026106
    }
  }
};

/**
 * Get a learned weight, falling back to the hand-tuned default if missing.
 */
export function getWeight(role, phase, feature, handTunedDefault) {
  const rw = LEARNED_WEIGHTS[role];
  if (!rw) return handTunedDefault;
  const pw = rw[phase];
  if (!pw) return handTunedDefault;
  const val = pw[feature];
  return val !== null && val !== undefined ? val : handTunedDefault;
}
