// Auto-generated by training/distill.py
// Do not edit manually -- re-run distillation to update.
//
// Distilled from checkpoint, 5 roles
// When a weight is null, the original hand-tuned value is used (fallback).

export const LEARNED_WEIGHTS = {
  "SNIPER": {
    "night": {
      "inverseSusp": 0.58416,
      "policeProb": 0.584546,
      "speakRatio": 0.0,
      "protectedPenalty": 0.165094,
      "grudgeAvoid": 0.135054
    }
  },
  "DOCTOR": {
    "night": {
      "policeProb": 0.063435,
      "blueProb": 0.35101,
      "speakRatio": 0.0,
      "votePressure": -0.002846
    }
  },
  "POLICE": {
    "night": {
      "killerProb": -0.211908,
      "sniperProb": -0.229884,
      "kidnapProb": -0.355916,
      "redProb": 0.028702,
      "silentRedLean": 0.0,
      "votePressure": 0.002232,
      "voteTogether": 0.005607
    }
  },
  "KILLER": {
    "night": {
      "policeProb": 0.130013,
      "doctorProb": 1.638513,
      "agentProb": 0.083712,
      "speakRatio": 0.0,
      "suspicion": 0.612114,
      "votePressure": -0.006528,
      "theyAccusedMe": 0.0,
      "voteTogether": -0.00199
    }
  }
};

/**
 * Get a learned weight, falling back to the hand-tuned default if missing.
 */
export function getWeight(role, phase, feature, handTunedDefault) {
  const rw = LEARNED_WEIGHTS[role];
  if (!rw) return handTunedDefault;
  const pw = rw[phase];
  if (!pw) return handTunedDefault;
  const val = pw[feature];
  return val !== null && val !== undefined ? val : handTunedDefault;
}
